# Generated by Django 5.0.4 on 2024-11-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueapp', '0002_produto_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
