# Generated by Django 5.0.4 on 2024-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueapp', '0005_fornecedor_produto_fornecido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='produto_fornecido',
            field=models.CharField(max_length=100),
        ),
    ]
